apiVersion: v1 
kind: Service
metadata:
  name: mynginx-svc
  labels:
     app: mynginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodeport: 30001 
  selector:
    app: mynginx